# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 06:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='标题')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_solve', models.BooleanField(default=False, verbose_name='处理?')),
                ('solve_date', models.DateField(blank=True, null=True, verbose_name='处理日期')),
                ('text', models.TextField(blank=True, null=True, verbose_name='正文')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='姓名')),
            ],
        ),
        migrations.CreateModel(
            name='PersonTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('is_solve', models.BooleanField(default=False, verbose_name='完成?')),
                ('url', models.URLField(blank=True, null=True, verbose_name='详细链接')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskCheck.Person', verbose_name='姓名')),
            ],
        ),
        migrations.CreateModel(
            name='PersonTaskList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskCheck.Person', verbose_name='姓名')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=120, verbose_name='标签')),
                ('is_alive', models.BooleanField(default=False, verbose_name='活动？')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=120, verbose_name='任务名称')),
                ('is_alive', models.BooleanField(default=False, verbose_name='活动？')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
        ),
        migrations.AddField(
            model_name='persontasklist',
            name='task',
            field=models.ManyToManyField(to='TaskCheck.Task', verbose_name='任务'),
        ),
        migrations.AddField(
            model_name='persontask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskCheck.Task', verbose_name='任务'),
        ),
        migrations.AddField(
            model_name='detailpost',
            name='create_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_create', to='TaskCheck.Person', verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='detailpost',
            name='solve_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_solve', to='TaskCheck.Person', verbose_name='处理人'),
        ),
        migrations.AddField(
            model_name='detailpost',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskCheck.Tag', verbose_name='标签'),
        ),
    ]
