# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 06:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TaskCheck', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='姓名'),
        ),
    ]
