# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskCheck', '0003_auto_20170317_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='describe',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='task',
            name='describe',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
    ]
