# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskCheck', '0004_auto_20170317_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='is_alive',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='is_alive',
            new_name='is_active',
        ),
        migrations.AlterField(
            model_name='persontask',
            name='is_solve',
            field=models.NullBooleanField(default=False, verbose_name='检查?'),
        ),
    ]
