# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskCheck', '0005_auto_20170317_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persontask',
            name='is_solve',
            field=models.NullBooleanField(default=None, verbose_name='检查?'),
        ),
    ]
