# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskCheck', '0007_auto_20170317_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailpost',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
