# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TaskCheck', '0008_auto_20170320_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persontask',
            name='url',
        ),
        migrations.AddField(
            model_name='detailpost',
            name='person_task',
            field=models.OneToOneField(default=12, on_delete=django.db.models.deletion.CASCADE, to='TaskCheck.PersonTask', verbose_name='任务详细'),
            preserve_default=False,
        ),
    ]
