# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TaskCheck', '0009_auto_20170321_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailpost',
            name='person_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskCheck.PersonTask', verbose_name='任务详细'),
        ),
    ]
